[general]
library_name = "libvic5"
output_file_path = "VIC5_api.jl"
module_name = "VIC5"
jll_pkg_name = "VIC5_jll"
export_symbol_prefixes = ["CX", "clang_"]
# extract_c_comment_style = "raw"

[codegen]
use_ccall_macro = true
use_julia_bool = true
always_NUL_terminated_string = true
is_function_strictly_typed = true
opaque_func_arg_as_PtrCvoid = false
opaque_as_mutable_struct = false
