name: CI

on:
  push:
    branches: [ "master", "classic", "image"]
  pull_request:
    branches: [ "master", "classic", "image"]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    #- name: configure
    #  run: ./configure
    - name: make
      run: 
        gcc --version; cd vic/drivers/classic && make
    #- name: make check
    #  run: make check
    #- name: make distcheck
    #  run: make distcheck
